name: fprettify-lint

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'

jobs:
    fprettify:
        name: fprettify-check
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
        defaults:
            run:
              shell: bash
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
      
           
            - name: Check for formatting differences
              run: |
                pip3 install fprettify
                if [[ $(fprettify  './src/' --config-file ./fprettify.config -d --recursive --case 1 1 1 1) ]]; then
                    fprettify  './src/' --config-file ./fprettify.config -d --recursive --case 1 1 1 1
                    exit 1
                else
                    echo "linting passed!"
                fi      
            