name: linux-nvidia-hpc-cmake

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  linux-tests:
    timeout-minutes: 20
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} - ${{ matrix.toolchain.compiler }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: nvidia-hpc, version: '23.11'}
        include:
            - os: ubuntu-22.04
              shell: bash
              build_type: debug
              toolchain: {compiler: nvidia-hpc, version: '23.11'}

    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Show version information
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version

      - name: Build with Cmake
        run: |
          export PATH=${PATH}:/opt/rocm/bin
          mkdir build
          cd build
          FC=${{ env.FC }} CC=${{ env.CC }} cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}  ../
          make VERBOSE=1

      - name: Run ctests
        run: |
          cd build/test
          ctest || ctest --rerun-failed --output-on-failure

